### ISSUE TITLE
Not compatible with the version of your running IDE (PyCharm 2022.1.4, IntelliJ IDEA 2022.2.3)

### ISSUE THREAD

**Issue by tungrix** [NikitaMishin/vyper-plugin#10]
I'm using IntelliJ IDEA 2022.2.3 (Ultimate Edition), it seems the plugin does not support this version; how can I solve it?

**Comment by mcpiatkowski** [comment]
Hello. @tungrix were you able to solve the issue? I am failing at building the plugin.

**Comment by NikitaMishin** [comment]
#11
