### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.2.1)

### ISSUE THREAD

**Issue by chuuuevi** [NikitaMishin/vyper-plugin#12]
@NikitaMishin Can you upload the latest version to plugins.jetbrains.com ?

url: https://plugins.jetbrains.com/plugin/19039-vyper/versions

**Comment by NikitaMishin** [comment]
yeap let me check, we will probably do this on weekends @chuuuevi

**Comment by NikitaMishin** [comment]
@chuuuevi   looks like some issues with project compatibility
if other contributors/maintainers have idea how to fix 
they are welcome
@Tiltedprogrammer  @rudolf101  @zishkaz

**Comment by DanielSchiavini** [comment]
I see that #11 was merged but not released.
I guess that this plugin needs some work done to work with the latest versions + it needs to be released and maintained.

@NikitaMishin Could I offer some help? Or should I try to rebuild the plugin by myself?

**Comment by NikitaMishin** [comment]
Hi! Contributors are welcomed! Yep, up to u to decide either fork or continue in this repo. Your call

> I see that #11 was merged but not released. I guess that this plugin needs some work done to work with the latest versions + it needs to be released and maintained.
> 
> @NikitaMishin Could I offer some help? Or should I try to rebuild the plugin by myself?

**Comment by NikitaMishin** [comment]
i think the developer who originally published to jetbrains market lost access to it

> that's great. I don't mind keeping the repo, but I wonder why hasn't the already merged stuff been released?

**Comment by NikitaMishin** [comment]
> that's great. I don't mind keeping the repo, but I wonder why hasn't the already merged stuff been released?

if you need i can give access for the repo maintenance, i doubt i would have time to help though. Maybe eventually would be more time rn pretty packed with deadlines:)

**Comment by DanielSchiavini** [comment]
No worries. If I get as far as to publish something to the market, it would need then to be a new plugin ID anyway.
It would be nice to automate the release process in a github action so we don't have this problem again.
I can do it in this repo or clone and make some PRs, or just publish from my fork. What do you prefer?

**Comment by NikitaMishin** [comment]
> DanielSchiavini

i think probably better keep things in one place, so if development continues in this repo then better to do in this repo,otherwise  if it continues from your fork then better to publish from fork

**Comment by DanielSchiavini** [comment]
I've created #13 and a few more issues. If you do not have the bandwidth to review/merge and/or configure the repo, please let me know and I'll continue in my fork
