### ISSUE TITLE
Autocompile on save

### ISSUE THREAD

**Issue by DanielSchiavini** [NikitaMishin/vyper-plugin#36]
- Automatically compile any vyper file when it's saved
- ~Use the JSON format so we can easily parse the results~ not possible, vyper returns no json for errors
- Add syntax highlighting for any errors and warnings found

**Comment by NikitaMishin** [comment]
for "Automatically compile any vyper file when it's saved" does IDE 
 fire events for each symbol user typed, if user enabled autosave? (scary we can introduce a lot of computation load)

Should we maybe automatically compile on manual save? when user hit ctrl+s for example? 

@DanielSchiavini , what do you think?

**Comment by DanielSchiavini** [comment]
Indeed, I am implementing an [external annotator](https://plugins.jetbrains.com/docs/intellij/syntax-highlighting-and-error-highlighting.html#external-annotator): _"The ExternalAnnotator highlighting has the lowest priority and is invoked only after all other background processing has completed"_
