### ISSUE TITLE
An error when install this plugin

### ISSUE THREAD

**Issue by xiangjianmeng** [NikitaMishin/vyper-plugin#4]
When I install the plugin in `./build/distributions/vyper-plugin-1.0-SNAPSHOT.zip`, I have encountered this error.
![image](https://user-images.githubusercontent.com/18412271/91058093-a51fef00-e65a-11ea-80da-10d09c0c9c29.png)

**Comment by emmick4** [comment]
Getting similar Error: `Plugin Error: Plugin "Vyper" is incompatible (until build 183.SNAPSHOT < PY-202.6397.98).`

**Comment by pavlovdog** [comment]
It would be amazing!

> @xiangjianmeng , @emmick4 , Hi guys, if there is still a need for such a plugin for the IntelliJ Platform, I guess, we can figure out how to deploy it to plugin store

**Comment by NikitaMishin** [comment]
Ok, I think, in September we will decide what steps should we need to perform (likely we will update the codebase and add new features)

**Comment by shekhirin** [comment]
@NikitaMishin any updates? 👀

**Comment by NikitaMishin** [comment]
@shekhirin  yep ppl start to doing it

**Comment by NikitaMishin** [comment]
@shekhirin  @pavlovdog @emmick4 @xiangjianmeng  https://github.com/NikitaMishin/vyper-plugin/pull/5 guys refactored code, so now it should work locally.  They now working on adding more features and pushing it to the market store.
The feedback will be extremely useful whether or not it correctly working

**Comment by elcolie** [comment]
How to install this plugin to PyCharm?

**Comment by NikitaMishin** [comment]
@elcolie  for now it is manually. https://intellij-support.jetbrains.com/hc/en-us/community/posts/206135879-How-to-install-plugin-manually- .Ppl now working on enhancing it and publishing it to jb plugin store. For checking u can clone project & follow readme

**Comment by elcolie** [comment]
@NikitaMishin I clone the repo and `Build > Rebuild project`. I don't see any zip file there.

**Comment by elcolie** [comment]
I found zip file
![image](https://user-images.githubusercontent.com/18206728/142339335-e0c196f2-9e34-4d6f-9103-b42a59de40ea.png)

And extract it under `plugins`
```bash
❯ ls
brokenPlugins.json            meta                          pluginsXMLIds.json.etag       vyper-plugin-1.1-SNAPSHOT.zip
brokenPlugins.json.etag       pluginsXMLIds.json            vyper-plugin
❯ pwd
/Users/sarit/Library/Application Support/JetBrains/IdeaIC2021.2/plugins
```

Plugin does not work

IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46)
Kotlin: 212-1.6.0-release-799-IJ5457.46

**Comment by pavlovdog** [comment]
HI @NikitaMishin ! any thoughts on when it'll be available in the store?  👀😊

**Comment by NikitaMishin** [comment]
@pavlovdog Hi,
Guys said that till the new year it should be pushed to market store.

Btw, do u have any suggestions on what we should add to plugin features,
We are open to any that will be useful for developers.

This question opened to anyone to give thoughts

**Comment by eugeneford** [comment]
@NikitaMishin, is there a way to make it compatible with PyCharm?

**Comment by eugeneford** [comment]
I've uncommented the https://github.com/NikitaMishin/vyper-plugin/blob/cf145db35bb0c2a1a5ab7d5e8fbb064463a39de9/src/main/resources/META-INF/plugin.xml#L10-L12 to make it launch in PyCharm, and it seems to be kinda working, but for some reason shows the following code is invalid:

```
event Transfer:
  _from: indexed(address)
 _to: indexed(address)
 _value: unit256
```

The `event` declaration displays as invalid with a `BadStatement` warning

**Comment by eugeneford** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/16384615/155376843-c7c8b3cf-9a09-41e6-b5c8-714431117af3.png">

**Comment by eugeneford** [comment]
@NikitaMishin, in terms of 

> Btw, do u have any suggestions on what we should add to plugin features,

I think it is unnecessary to include the Vyper compiler inside the plugin considering that we nowadays have Brownie. I'd recommend removing it from the plugin and limiting the plugin functionality to the same scope solidity plugin has:
1. Syntax highlighting
2. Code completion
3. File templates
4. Goto declaration
5. Find usages
6. Code formatting

**Comment by salian** [comment]
+1 with @eugeneford 's line of thought. Its better to have a simple plugin that's shipped. The temptation to add more features is a trap.

Also compatibility with PyCharm should be very high on the list.

**Comment by rudolf101** [comment]
Our plugin has finally made it to the JetBrains Marketplace release. Waiting for your feedback!

<p align="center">
  <a href="https://plugins.jetbrains.com/plugin/19039-vyper">
         <img alt="Download from JetBrains Marketplace" src="https://user-images.githubusercontent.com/70969943/169074594-1e1b8769-01f7-49a1-8dac-e7a056c4c274.png">
</a>
</p>

**Comment by NikitaMishin** [comment]
closing cause we pushed  it to the marketplace
