### ISSUE TITLE
error to install in pycharm

### ISSUE THREAD

**Issue by scwall** [NikitaMishin/vyper-plugin#6]
Hello after a build under pycharm 2021.2.3 I get this error after installation. it seems that this one is not supported
![image](https://user-images.githubusercontent.com/30811539/142760185-3014ece7-8edb-42c0-8501-0e63cc4b5654.png)

![Capture d’écran 2021-11-21 123008](https://user-images.githubusercontent.com/30811539/142760132-deec46b1-a8ea-4710-aa89-6953b3131bd4.png)

![image](https://user-images.githubusercontent.com/30811539/142760159-21c29019-45b1-4e71-ba5a-92c2e6c40325.png)

Thank's in advance

**Comment by NikitaMishin** [comment]
@zishkaz @rudolf101 Do u have suggestions for @scwall ?

**Comment by rudolf101** [comment]
We found what the problem is, we are working on a fix, thank you!

**Comment by rudolf101** [comment]
We found out that the plugin is currently not supported in PyCharm, so we apologize for the incorrect information in  #4. The addition of full-fledged PyCharm support is planned for the future. We will definitely inform you as soon as we do.

Currently, the plugin is only supported in IntelliJ IDEA, so you can still use it.

Thank you for the feedback!

**Comment by scwall** [comment]
Thank you for your answer, I look for another use

**Comment by tungrix** [comment]
May I ask does this plugin support Pycharm now? I am looking for a Vyper plugin-supported Pycharm. @rudolf101

**Comment by rudolf101** [comment]
> May I ask does this plugin support Pycharm now? I am looking for a Vyper plugin-supported Pycharm. @rudolf101 

Hello, unfortunately, the plugin is not supported in PyCharm. 

I can't say if the plugin will go beyond the IntelliJ IDEA. Definitely not at the moment.
