### ISSUE TITLE
Can you upload a compiled file？

### ISSUE THREAD

**Issue by skyhuihui** [NikitaMishin/vyper-plugin#8]
Can you upload a compiled file

**Comment by zishkaz** [comment]
> Can you upload a compiled file

Hello! Yes, here you go: a compiled plugin for Intellij IDEA version 2021.3. However, when idea updates to a newer version, this file won't work. We strongly recommend to build the pl
[vyper-plugin-1.2-SNAPSHOT.zip](https://github.com/NikitaMishin/vyper-plugin/files/8055266/vyper-plugin-1.2-SNAPSHOT.zip)
ugin yourself as described in readme while we are working on pushing it to the plugin market.

**Comment by NikitaMishin** [comment]
close cause we pushed plugin to IntelliJ store
